//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "alwa_offers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub listing_id: i32,
    pub buyer_phone: String,
    pub buyer_name: String,
    pub buyer_kind: String,
    pub quantity_kg: i32,
    pub price_iqd_per_kg: i32,
    pub status: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::alwa_listings::Entity",
        from = "Column::ListingId",
        to = "super::alwa_listings::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AlwaListings,
}

impl Related<super::alwa_listings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlwaListings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
