//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "alwa_markets")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub slug: String,
    pub name_en: String,
    pub name_ku: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::alwa_listings::Entity")]
    AlwaListings,
    #[sea_orm(has_many = "super::alwa_prices::Entity")]
    AlwaPrices,
}

impl Related<super::alwa_listings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlwaListings.def()
    }
}

impl Related<super::alwa_prices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlwaPrices.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
