//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "alwa_listings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "idx_alwa_listings_seller_phone_idempotency_key")]
    pub seller_phone: String,
    pub seller_name: Option<String>,
    pub crop: String,
    pub quantity_kg: i32,
    pub asking_price_iqd_per_kg: i32,
    pub grade: Option<String>,
    pub pickup: String,
    pub market_id: i32,
    pub zone_slug: Option<String>,
    pub note: Option<String>,
    pub closes_at: DateTime,
    pub status: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(unique_key = "idx_alwa_listings_seller_phone_idempotency_key")]
    pub idempotency_key: Option<String>,
    pub closed_by_staff_id: Option<i32>,
    pub moderation_note: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::alwa_markets::Entity",
        from = "Column::MarketId",
        to = "super::alwa_markets::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    AlwaMarkets,
    #[sea_orm(has_many = "super::alwa_offers::Entity")]
    AlwaOffers,
}

impl Related<super::alwa_markets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlwaMarkets.def()
    }
}

impl Related<super::alwa_offers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlwaOffers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
