//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "alwa_prices")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "idx_alwa_prices_market_id_crop_day")]
    pub market_id: i32,
    #[sea_orm(unique_key = "idx_alwa_prices_market_id_crop_day")]
    pub crop: String,
    #[sea_orm(unique_key = "idx_alwa_prices_market_id_crop_day")]
    pub day: Date,
    pub price_iqd_per_kg: i32,
    pub fixed: bool,
    pub source: String,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::alwa_markets::Entity",
        from = "Column::MarketId",
        to = "super::alwa_markets::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    AlwaMarkets,
}

impl Related<super::alwa_markets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlwaMarkets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
