//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "farms")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(unique_key = "idx_farms_phone_idempotency_key")]
    pub phone: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub outline: Json,
    #[sea_orm(unique_key = "idx_farms_phone_idempotency_key")]
    pub idempotency_key: Option<String>,
    pub created_offline_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub governorate: Option<String>,
    pub zone_slug: Option<String>,
    pub sub_zone_slug: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub area_m2: Option<f64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::farm_cells::Entity")]
    FarmCells,
}

impl Related<super::farm_cells::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FarmCells.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
