//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "farm_cells")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "idx_farm_cells_farm_id_e_n")]
    pub farm_id: i32,
    #[sea_orm(unique_key = "idx_farm_cells_farm_id_e_n")]
    pub e: i32,
    #[sea_orm(unique_key = "idx_farm_cells_farm_id_e_n")]
    pub n: i32,
    pub crop: String,
    #[sea_orm(column_type = "Double")]
    pub inside_pct: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::farms::Entity",
        from = "Column::FarmId",
        to = "super::farms::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Farms,
}

impl Related<super::farms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Farms.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
