//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "farm_history_series")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub farm_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub metric: String,
    pub unit: String,
    pub source: String,
    pub as_of: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
