//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "farm_history")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub farm_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub metric: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub month: Date,
    #[sea_orm(column_type = "Double")]
    pub value: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
