//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "sub_zones")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "idx_sub_zones_zone_id_slug")]
    pub zone_id: i32,
    #[sea_orm(unique_key = "idx_sub_zones_zone_id_slug")]
    pub slug: String,
    pub name_en: String,
    pub name_ku: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::sub_zone_readings::Entity")]
    SubZoneReadings,
    #[sea_orm(
        belongs_to = "super::zones::Entity",
        from = "Column::ZoneId",
        to = "super::zones::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Zones,
}

impl Related<super::sub_zone_readings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubZoneReadings.def()
    }
}

impl Related<super::zones::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Zones.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
