//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "sub_zone_readings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "idx_sub_zone_readings_sub_zone_id_month")]
    pub sub_zone_id: i32,
    #[sea_orm(unique_key = "idx_sub_zone_readings_sub_zone_id_month")]
    pub month: Date,
    pub dryness: i32,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sub_zones::Entity",
        from = "Column::SubZoneId",
        to = "super::sub_zones::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SubZones,
}

impl Related<super::sub_zones::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubZones.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
