//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "zones")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub slug: String,
    pub name_en: String,
    pub name_ku: String,
    pub governorate: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::sub_zones::Entity")]
    SubZones,
    #[sea_orm(has_many = "super::zone_readings::Entity")]
    ZoneReadings,
}

impl Related<super::sub_zones::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubZones.def()
    }
}

impl Related<super::zone_readings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ZoneReadings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
