//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "zone_readings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "idx_zone_readings_zone_id_month")]
    pub zone_id: i32,
    #[sea_orm(unique_key = "idx_zone_readings_zone_id_month")]
    pub month: Date,
    pub dryness: i32,
    #[sea_orm(column_type = "Double", nullable)]
    pub rain_pct_of_normal: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub greenness_pct_vs_normal: Option<f64>,
    pub water_need: Option<i32>,
    pub nitrogen_hold: bool,
    #[sea_orm(column_type = "JsonBinary")]
    pub best_crops: Json,
    pub source: String,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::zones::Entity",
        from = "Column::ZoneId",
        to = "super::zones::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Zones,
}

impl Related<super::zones::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Zones.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
