//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "water_plan_entries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "idx_water_plan_entries_season_zone_slug")]
    pub season: String,
    #[sea_orm(unique_key = "idx_water_plan_entries_season_zone_slug")]
    pub zone_slug: String,
    #[sea_orm(column_type = "Double")]
    pub need: f64,
    pub dam_slug: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub send_million_m3: Option<f64>,
    pub urgent: bool,
    pub note_en: Option<String>,
    pub note_ku: Option<String>,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
