//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "daily_briefs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "idx_daily_briefs_scope_day")]
    pub day: Date,
    #[sea_orm(unique_key = "idx_daily_briefs_scope_day")]
    pub scope: String,
    pub headline_en: String,
    pub headline_ku: String,
    pub summary_en: String,
    pub summary_ku: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub points: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub sources: Json,
    pub author: String,
    pub generated_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
