//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "job_runs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "idx_job_runs_job_started_at")]
    pub job: String,
    #[sea_orm(unique_key = "idx_job_runs_job_started_at")]
    pub started_at: DateTime,
    pub finished_at: Option<DateTime>,
    pub ok: Option<bool>,
    pub rows: Option<i64>,
    pub message: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::jobs::Entity",
        from = "Column::Job",
        to = "super::jobs::Column::Job",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Jobs,
}

impl Related<super::jobs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Jobs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
