//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "jobs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub job: String,
    pub name_en: String,
    pub name_ku: Option<String>,
    pub every_hours: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::job_runs::Entity")]
    JobRuns,
}

impl Related<super::job_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JobRuns.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
