use utoipa::{
    Modify, OpenApi,
    openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme},
};
use utoipa_swagger_ui::SwaggerUi;

use crate::features::{
    farmers::web::{
        DashboardCreateFarmerParams, DashboardFarmerResponse, DashboardFarmersResponse,
        DashboardOneFarmerResponse, DashboardUpdateFarmerParams,
    },
    farms::web::{
        DashboardCreateFarmParams, DashboardFarmResponse, DashboardFarmSummaryResponse,
        DashboardFarmsResponse, DashboardOneFarmResponse, DashboardRenameFarmParams,
        DashboardSavedFarmResponse,
    },
};
use crate::{
    features::alwa::web::{
        AlwaBuyerKind, AlwaCrop, AlwaDealResponse, AlwaDealsResponse, AlwaDealsSummaryResponse,
        AlwaFairPrice, AlwaGrade, AlwaListingResponse, AlwaListingStatus,
        AlwaListingSummaryResponse, AlwaListingsResponse, AlwaMarketPricesResponse,
        AlwaMarketResponse, AlwaMarketsResponse, AlwaMyListingsResponse, AlwaMyOfferResponse,
        AlwaMyOffersResponse, AlwaOfferListingResponse, AlwaOfferResponse, AlwaOfferStatus,
        AlwaOneListingResponse, AlwaOneOfferResponse, AlwaOnePriceResponse, AlwaPickup,
        AlwaPriceHistoryResponse, AlwaPricePointResponse, AlwaPriceResponse,
        AlwaRecordedPriceResponse, MakeAlwaOfferParams, PostAlwaListingParams,
        RecordAlwaPriceParams, handlers as alwa_handlers,
    },
    features::dams::web::{
        CreateDamDashboardReadingParams, DamHistoryResponse, DamReadingResponse,
        DamReadingsPageResponse, DamReferenceResponse, DamReferencesResponse, DamResponse,
        DamsResponse, HistoryReadingResponse, LatestReadingResponse, RecordDamReadingParams,
        SavedDamReadingResponse, YearAgoReadingResponse, handlers as dam_handlers,
    },
    features::farmers::web::{
        EditProfileParams, Language, ProfileResponse, SendSignInCodeParams, SignInCodeSentResponse,
        SignedInResponse, VerifySignInCodeParams, handlers as farmer_handlers,
    },
    features::farms::web::{
        CellParams, CellResponse, CellStatusResponse, CentroidResponse, CreateFarmParams, Crop,
        CropAreaResponse, CropStatusResponse, FarmResponse, FarmStatusResponse,
        FarmSummaryResponse, FarmsResponse, GridCellResponse, Level, OneFarmResponse,
        OutlinePointResponse, PointParams, RepaintFarmCellsParams, SavedFarmResponse,
        handlers as farm_handlers,
    },
    features::fires::web::{
        FireDashboardCreateParams, FireDashboardListResponse, FireDashboardOneResponse,
        FireDashboardResponse, FireResponse, FireStatus, FireSummaryResponse, FiresResponse,
        RecordFireParams, WindDirection, handlers as fire_handlers,
    },
    features::insights::web::{
        Confidence, FarmCoverageResponse, FarmInsightsResponse, FarmsCoverageResponse,
        InsightDashboardCreateParams, InsightDashboardListResponse, InsightDashboardOneResponse,
        InsightDashboardResponse, MeasureParams, MeasureResponse, RecordFarmInsightParams, Topic,
        TopicInsightResponse, TopicStampResponse, handlers as insight_handlers,
    },
    features::outlooks::web::{
        CreateOutlookDashboardParams, CreateOutlookRunDashboardParams, Outlook,
        OutlookCountsResponse, OutlookRunResponse, OutlookRunsResponse, OutlooksPageResponse,
        RecordOutlookRunParams, RecordZoneOutlookParams, SavedOutlookRunResponse,
        SavedZoneOutlookResponse, SeasonOutlookResponse, StoredZoneOutlookResponse,
        TrackRecordResponse, ZoneIssueResponse, ZoneOutlookHistoryResponse, ZoneOutlookResponse,
        handlers as outlook_handlers,
    },
    features::staff::web::{
        CreateStaffParams, SaveStaffRoleParams, StaffAction, StaffListResponse, StaffLoginParams,
        StaffMeResponse, StaffOneResponse, StaffOneRoleResponse, StaffPermission,
        StaffPermissionCatalogueResponse, StaffResource, StaffResponse, StaffRoleRefResponse,
        StaffRoleResponse, StaffRolesResponse, StaffSignedInResponse, UpdateStaffParams,
        handlers as staff_handlers,
    },
    features::water::web::{
        CreateWaterPlanEntryDashboardParams, DamAllocationResponse, PlanTotalsResponse,
        RankedEntryResponse, SavedWaterPlanEntryResponse, SetWaterPlanEntryParams,
        StoredWaterPlanEntryResponse, WaterPlanEntriesResponse, WaterPlanResponse,
        WaterSeasonsResponse, handlers as water_handlers,
    },
    features::zones::web::{
        BestCrop, CreateZoneDashboardReadingParams, CreateZoneDashboardSubZoneReadingParams,
        DrynessBand, RegionComparisonResponse, RegionOverviewResponse, RegionSummaryResponse,
        SubZoneDrynessResponse, SubZoneReadingParams, SubZoneReadingResponse, YearAverageResponse,
        YearDrynessResponse, ZoneComparisonResponse, ZoneDashboardReadingsResponse,
        ZoneDashboardSubZoneReadingsResponse, ZoneDashboardSubZoneResponse,
        ZoneDashboardZoneResponse, ZoneDashboardZonesResponse, ZoneDetailReadingResponse,
        ZoneDetailResponse, ZoneOverviewResponse, ZoneReadingParams, ZoneReadingResponse,
        handlers as zone_handlers,
    },
    infra::http::{ErrorBody, health},
};

struct BearerAuth;

impl Modify for BearerAuth {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_with(Default::default);

        components.add_security_scheme(
            "bearer_auth",
            SecurityScheme::Http(
                HttpBuilder::new()
                    .scheme(HttpAuthScheme::Bearer)
                    .bearer_format("JWT")
                    .build(),
            ),
        );
    }
}

#[derive(OpenApi)]
#[openapi(
    paths(
        farm_handlers::get_farms,
        farm_handlers::create_farm,
        farm_handlers::get_farm,
        farm_handlers::get_farm_status,
        farm_handlers::repaint_farm_cells,
        farm_handlers::delete_farm,
        farmer_handlers::send_sign_in_code,
        farmer_handlers::verify_sign_in_code,
        farmer_handlers::get_profile,
        farmer_handlers::update_profile,
        fire_handlers::get_fires,
        fire_handlers::put_fire,
        insight_handlers::get_farm_insights,
        insight_handlers::get_farm_coverage,
        insight_handlers::put_farm_insight,
        zone_handlers::get_region_overview,
        zone_handlers::get_zone,
        zone_handlers::get_region_comparison,
        zone_handlers::put_zone_reading,
        zone_handlers::put_sub_zone_reading,
        dam_handlers::get_dams,
        dam_handlers::get_dam_history,
        dam_handlers::put_dam_reading,
        outlook_handlers::get_season_outlook,
        outlook_handlers::get_zone_outlook,
        outlook_handlers::put_zone_outlook,
        outlook_handlers::put_outlook_run,
        water_handlers::get_water_plan,
        water_handlers::put_water_plan_entry,
        water_handlers::delete_water_plan_entry,
        alwa_handlers::get_markets,
        alwa_handlers::get_market_prices,
        alwa_handlers::get_price_history,
        alwa_handlers::get_listings,
        alwa_handlers::get_listing,
        alwa_handlers::get_deals,
        alwa_handlers::create_listing,
        alwa_handlers::get_my_listings,
        alwa_handlers::cancel_listing,
        alwa_handlers::create_offer,
        alwa_handlers::accept_offer,
        alwa_handlers::get_my_offers,
        alwa_handlers::put_price,
        staff_handlers::sign_in,
        staff_handlers::get_me,
        staff_handlers::get_permission_catalogue,
        staff_handlers::get_roles,
        staff_handlers::create_role,
        staff_handlers::get_role,
        staff_handlers::update_role,
        staff_handlers::delete_role,
        staff_handlers::get_staff_list,
        staff_handlers::create_staff,
        staff_handlers::get_staff,
        staff_handlers::update_staff,
        staff_handlers::delete_staff,
        health::liveness,
        health::readiness,
        fire_handlers::get_dashboard_fires,
        fire_handlers::get_dashboard_fire,
        fire_handlers::create_dashboard_fire,
        fire_handlers::update_dashboard_fire,
        fire_handlers::delete_dashboard_fire,
        insight_handlers::get_dashboard_farm_insights,
        insight_handlers::create_dashboard_farm_insight,
        insight_handlers::update_dashboard_farm_insight,
        insight_handlers::delete_dashboard_farm_insight,
        zone_handlers::get_dashboard_zones,
        zone_handlers::get_dashboard_zone_readings,
        zone_handlers::create_dashboard_zone_reading,
        zone_handlers::update_dashboard_zone_reading,
        zone_handlers::delete_dashboard_zone_reading,
        zone_handlers::get_dashboard_sub_zone_readings,
        zone_handlers::create_dashboard_sub_zone_reading,
        zone_handlers::update_dashboard_sub_zone_reading,
        zone_handlers::delete_dashboard_sub_zone_reading,
        farmer_handlers::dashboard_get_farmers,
        farmer_handlers::dashboard_create_farmer,
        farmer_handlers::dashboard_get_farmer,
        farmer_handlers::dashboard_update_farmer,
        farmer_handlers::dashboard_delete_farmer,
        farm_handlers::dashboard_get_farms,
        farm_handlers::dashboard_create_farm,
        farm_handlers::dashboard_get_farm,
        farm_handlers::dashboard_rename_farm,
        farm_handlers::dashboard_delete_farm,
        dam_handlers::dashboard_get_dams,
        dam_handlers::dashboard_get_dam_readings,
        dam_handlers::dashboard_create_dam_reading,
        dam_handlers::dashboard_update_dam_reading,
        dam_handlers::dashboard_delete_dam_reading,
        outlook_handlers::dashboard_get_outlooks,
        outlook_handlers::dashboard_create_outlook,
        outlook_handlers::dashboard_update_outlook,
        outlook_handlers::dashboard_delete_outlook,
        outlook_handlers::dashboard_get_outlook_runs,
        outlook_handlers::dashboard_create_outlook_run,
        outlook_handlers::dashboard_update_outlook_run,
        outlook_handlers::dashboard_delete_outlook_run,
        water_handlers::dashboard_get_water_seasons,
        water_handlers::dashboard_get_water_plan_entries,
        water_handlers::dashboard_create_water_plan_entry,
        water_handlers::dashboard_update_water_plan_entry,
        water_handlers::dashboard_delete_water_plan_entry
    ),
    components(schemas(
        CreateFarmParams,
        RepaintFarmCellsParams,
        PointParams,
        CellParams,
        FarmSummaryResponse,
        FarmResponse,
        SavedFarmResponse,
        CropAreaResponse,
        CentroidResponse,
        OutlinePointResponse,
        CellResponse,
        GridCellResponse,
        Crop,
        FarmsResponse,
        OneFarmResponse,
        SendSignInCodeParams,
        SignInCodeSentResponse,
        VerifySignInCodeParams,
        SignedInResponse,
        EditProfileParams,
        ProfileResponse,
        Language,
        RecordFireParams,
        FireResponse,
        FireSummaryResponse,
        FiresResponse,
        FireStatus,
        WindDirection,
        RecordFarmInsightParams,
        MeasureParams,
        MeasureResponse,
        TopicInsightResponse,
        FarmInsightsResponse,
        TopicStampResponse,
        FarmCoverageResponse,
        FarmsCoverageResponse,
        Topic,
        Confidence,
        RegionOverviewResponse,
        ZoneOverviewResponse,
        RegionSummaryResponse,
        ZoneDetailResponse,
        ZoneDetailReadingResponse,
        SubZoneDrynessResponse,
        YearDrynessResponse,
        RegionComparisonResponse,
        ZoneComparisonResponse,
        YearAverageResponse,
        ZoneReadingParams,
        ZoneReadingResponse,
        SubZoneReadingParams,
        SubZoneReadingResponse,
        DrynessBand,
        BestCrop,
        DamsResponse,
        DamResponse,
        LatestReadingResponse,
        YearAgoReadingResponse,
        DamHistoryResponse,
        HistoryReadingResponse,
        RecordDamReadingParams,
        SavedDamReadingResponse,
        DamReadingResponse,
        SeasonOutlookResponse,
        OutlookCountsResponse,
        ZoneOutlookResponse,
        TrackRecordResponse,
        ZoneOutlookHistoryResponse,
        ZoneIssueResponse,
        RecordZoneOutlookParams,
        SavedZoneOutlookResponse,
        StoredZoneOutlookResponse,
        RecordOutlookRunParams,
        SavedOutlookRunResponse,
        OutlookRunResponse,
        Outlook,
        WaterPlanResponse,
        RankedEntryResponse,
        PlanTotalsResponse,
        DamAllocationResponse,
        SetWaterPlanEntryParams,
        SavedWaterPlanEntryResponse,
        StoredWaterPlanEntryResponse,
        FarmStatusResponse,
        CropStatusResponse,
        CellStatusResponse,
        Level,
        AlwaCrop,
        AlwaGrade,
        AlwaPickup,
        AlwaListingStatus,
        AlwaOfferStatus,
        AlwaBuyerKind,
        AlwaFairPrice,
        AlwaMarketResponse,
        AlwaMarketsResponse,
        AlwaPriceResponse,
        AlwaMarketPricesResponse,
        AlwaPricePointResponse,
        AlwaPriceHistoryResponse,
        RecordAlwaPriceParams,
        AlwaRecordedPriceResponse,
        AlwaOnePriceResponse,
        AlwaListingSummaryResponse,
        AlwaListingsResponse,
        PostAlwaListingParams,
        AlwaListingResponse,
        AlwaOneListingResponse,
        AlwaMyListingsResponse,
        MakeAlwaOfferParams,
        AlwaOfferResponse,
        AlwaOneOfferResponse,
        AlwaOfferListingResponse,
        AlwaMyOfferResponse,
        AlwaMyOffersResponse,
        AlwaDealResponse,
        AlwaDealsSummaryResponse,
        AlwaDealsResponse,
        StaffLoginParams,
        StaffSignedInResponse,
        StaffMeResponse,
        StaffPermissionCatalogueResponse,
        StaffPermission,
        StaffResource,
        StaffAction,
        StaffResponse,
        StaffRoleRefResponse,
        StaffOneResponse,
        StaffListResponse,
        CreateStaffParams,
        UpdateStaffParams,
        SaveStaffRoleParams,
        StaffRoleResponse,
        StaffOneRoleResponse,
        StaffRolesResponse,
        FireDashboardCreateParams,
        FireDashboardResponse,
        FireDashboardOneResponse,
        FireDashboardListResponse,
        InsightDashboardCreateParams,
        InsightDashboardResponse,
        InsightDashboardOneResponse,
        InsightDashboardListResponse,
        ZoneDashboardZonesResponse,
        ZoneDashboardZoneResponse,
        ZoneDashboardSubZoneResponse,
        ZoneDashboardReadingsResponse,
        ZoneDashboardSubZoneReadingsResponse,
        CreateZoneDashboardReadingParams,
        CreateZoneDashboardSubZoneReadingParams,
        DashboardCreateFarmerParams,
        DashboardUpdateFarmerParams,
        DashboardFarmerResponse,
        DashboardOneFarmerResponse,
        DashboardFarmersResponse,
        DashboardCreateFarmParams,
        DashboardRenameFarmParams,
        DashboardFarmSummaryResponse,
        DashboardFarmsResponse,
        DashboardFarmResponse,
        DashboardOneFarmResponse,
        DashboardSavedFarmResponse,
        CreateDamDashboardReadingParams,
        DamReferenceResponse,
        DamReferencesResponse,
        DamReadingsPageResponse,
        CreateOutlookDashboardParams,
        CreateOutlookRunDashboardParams,
        OutlooksPageResponse,
        OutlookRunsResponse,
        CreateWaterPlanEntryDashboardParams,
        WaterSeasonsResponse,
        WaterPlanEntriesResponse,
        ErrorBody
    )),
    modifiers(&BearerAuth),
    tags(
        (name = "farm-doctor-api", description = "Farm Doctor API"),
        (name = "farmers", description = "Sign in with a phone and a code, and the farmer's profile"),
        (name = "farms", description = "A farmer's farms: outline, cell grid and crops"),
        (name = "fires", description = "Satellite fire detections for the Ministry dashboard"),
        (name = "insights", description = "What the data jobs know about a farm, topic by topic"),
        (name = "zones", description = "The region's districts: dryness, rain, greenness and advice per month"),
        (name = "dams", description = "The large dams: how full they are now, a year ago and over time"),
        (name = "outlooks", description = "The Doctor: the outlook for the next growing season, zone by zone"),
        (name = "water", description = "The plan for which zones should receive water first"),
        (name = "alwa", description = "The wholesale produce markets: prices, crops on sale, offers and deals"),
        (name = "staff", description = "The dashboard's staff accounts, custom roles and sign-in")
    ),
    info(
        title = "farm-doctor-api",
        version = "1.0.0",
        description = "API behind the farmer app and the Ministry dashboard."
    ),
    servers((url = "/", description = "API"))
)]
pub struct ApiDoc;

pub fn swagger_ui() -> SwaggerUi {
    SwaggerUi::new("/api-docs").url("/api-docs/openapi.json", ApiDoc::openapi())
}
