use utoipa::{
    Modify, OpenApi,
    openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme},
};
use utoipa_swagger_ui::SwaggerUi;

use crate::features::alwa::web::{
    AlwaModeratedListingDetailResponse, AlwaModeratedListingResponse,
    AlwaModeratedListingsResponse, AlwaModeratedOfferResponse, AlwaOneMarketResponse,
    AlwaOneModeratedListingResponse, AlwaStoredPricesResponse, CreateAlwaMarketParams,
    CreateAlwaPriceParams, ModerateAlwaListingParams, UpdateAlwaMarketParams,
    dashboard_handlers as alwa_dashboard_handlers,
};
use crate::features::{
    doctor::web::{
        DoctorAnswerResponse, DoctorAskForm, DoctorConfidence, handlers as doctor_handlers,
    },
    farmers::web::{
        DashboardCreateFarmerParams, DashboardFarmerOrder, DashboardFarmerResponse,
        DashboardFarmerSort, DashboardFarmersResponse, DashboardIssueLetterParams,
        DashboardIssuedLetterResponse, DashboardLetterCropResponse, DashboardLetterFarmResponse,
        DashboardLetterFarmerResponse, DashboardLetterIssuerResponse,
        DashboardLetterRecordResponse, DashboardLetterTotalsResponse, DashboardOneFarmerResponse,
        DashboardOneIssuedLetterResponse, DashboardOneLetterRecordResponse,
        DashboardUpdateFarmerParams, FarmerGender, FarmerLetterLanguage,
    },
    farms::web::{
        DashboardCreateFarmParams, DashboardFarmResponse, DashboardFarmSummaryResponse,
        DashboardFarmsResponse, DashboardOneFarmResponse, DashboardRenameFarmParams,
        DashboardSavedFarmResponse,
    },
};
use crate::{
    features::alwa::web::{
        AlwaBuyerKind, AlwaDealResponse, AlwaDealsResponse, AlwaDealsSummaryResponse,
        AlwaFairPrice, AlwaGrade, AlwaListingResponse, AlwaListingStatus,
        AlwaListingSummaryResponse, AlwaListingsResponse, AlwaMarketPricesResponse,
        AlwaMarketResponse, AlwaMarketsResponse, AlwaMyListingsResponse, AlwaMyOfferResponse,
        AlwaMyOffersResponse, AlwaOfferListingResponse, AlwaOfferResponse, AlwaOfferStatus,
        AlwaOneListingResponse, AlwaOneOfferResponse, AlwaOnePriceResponse, AlwaPickup,
        AlwaPriceHistoryResponse, AlwaPricePointResponse, AlwaPriceResponse, AlwaProductGroup,
        AlwaRecordedPriceResponse, AlwaUnit, MakeAlwaOfferParams, PostAlwaListingParams,
        RecordAlwaPriceParams, handlers as alwa_handlers,
    },
    features::briefs::web::{
        BriefFarmZoneParams, BriefFarmZonesRecordedResponse, BriefPointLevel, BriefPointParams,
        BriefPointResponse, BriefResponse, BriefSourceParams, BriefSourceResponse,
        BriefsPageResponse, BriefsResponse, FarmBriefResponse, OneBriefResponse,
        RecordBriefFarmZonesParams, RecordBriefParams, handlers as brief_handlers,
    },
    features::dams::web::{
        CreateDamDashboardReadingParams, DamHistoryResponse, DamReadingResponse,
        DamReadingsPageResponse, DamReferenceResponse, DamReferencesResponse, DamResponse,
        DamsResponse, HistoryReadingResponse, LatestReadingResponse, RecordDamReadingParams,
        SavedDamReadingResponse, YearAgoReadingResponse, handlers as dam_handlers,
    },
    features::farmers::web::{
        EditProfileParams, Language, ProfileResponse, SendSignInCodeParams, SignInCodeSentResponse,
        SignedInResponse, VerifySignInCodeParams, handlers as farmer_handlers,
    },
    features::farms::web::{
        CellParams, CellResponse, CellStatusResponse, CentroidResponse, CreateFarmParams,
        CropAreaResponse, CropStatusResponse, FarmResponse, FarmStatusResponse,
        FarmSummaryResponse, FarmsResponse, GridCellResponse, Level, OneFarmResponse,
        OutlinePointResponse, PointParams, RepaintFarmCellsParams, SavedFarmResponse,
        handlers as farm_handlers,
    },
    features::fires::web::{
        FireDashboardCreateParams, FireDashboardListResponse, FireDashboardOneResponse,
        FireDashboardResponse, FireResponse, FireStatus, FireSummaryResponse, FiresResponse,
        RecordFireParams, WindDirection, handlers as fire_handlers,
    },
    features::insights::web::{
        Confidence, FarmCoverageResponse, FarmInsightsResponse, FarmsCoverageResponse,
        InsightDashboardCreateParams, InsightDashboardListResponse, InsightDashboardOneResponse,
        InsightDashboardResponse, MeasureParams, MeasureResponse, RecordFarmInsightParams, Topic,
        TopicInsightResponse, TopicStampResponse, handlers as insight_handlers,
    },
    features::outlooks::web::{
        CreateOutlookDashboardParams, CreateOutlookRunDashboardParams, Outlook,
        OutlookCountsResponse, OutlookRunResponse, OutlookRunsResponse, OutlooksPageResponse,
        RecordOutlookRunParams, RecordZoneOutlookParams, SavedOutlookRunResponse,
        SavedZoneOutlookResponse, SeasonOutlookResponse, StoredZoneOutlookResponse,
        TrackRecordResponse, ZoneIssueResponse, ZoneOutlookHistoryResponse, ZoneOutlookResponse,
        handlers as outlook_handlers,
    },
    features::staff::web::{
        CreateStaffParams, SaveStaffRoleParams, StaffAction, StaffListResponse, StaffLoginParams,
        StaffMeResponse, StaffOneResponse, StaffOneRoleResponse, StaffPermission,
        StaffPermissionCatalogueResponse, StaffResource, StaffResponse, StaffRoleRefResponse,
        StaffRoleResponse, StaffRolesResponse, StaffSignedInResponse, UpdateOwnStaffProfileParams,
        UpdateStaffParams, handlers as staff_handlers,
    },
    features::water::web::{
        CreateWaterPlanEntryDashboardParams, DamAllocationResponse, PlanTotalsResponse,
        RankedEntryResponse, SavedWaterPlanEntryResponse, SetWaterPlanEntryParams,
        StoredWaterPlanEntryResponse, WaterPlanEntriesResponse, WaterPlanResponse,
        WaterSeasonsResponse, handlers as water_handlers,
    },
    features::zones::web::{
        BestCrop, CreateZoneDashboardReadingParams, CreateZoneDashboardSubZoneReadingParams,
        DrynessBand, RegionComparisonResponse, RegionOverviewResponse, RegionSummaryResponse,
        SubZoneDrynessResponse, SubZoneReadingParams, SubZoneReadingResponse, YearAverageResponse,
        YearDrynessResponse, ZoneComparisonResponse, ZoneDashboardReadingsResponse,
        ZoneDashboardSubZoneReadingsResponse, ZoneDashboardSubZoneResponse,
        ZoneDashboardZoneResponse, ZoneDashboardZonesResponse, ZoneDetailReadingResponse,
        ZoneDetailResponse, ZoneOverviewResponse, ZoneReadingParams, ZoneReadingResponse,
        handlers as zone_handlers,
    },
    infra::http::{ErrorBody, health},
};

struct BearerAuth;

impl Modify for BearerAuth {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_with(Default::default);

        components.add_security_scheme(
            "bearer_auth",
            SecurityScheme::Http(
                HttpBuilder::new()
                    .scheme(HttpAuthScheme::Bearer)
                    .bearer_format("JWT")
                    .build(),
            ),
        );
    }
}

#[derive(OpenApi)]
#[openapi(
    paths(
        farm_handlers::get_farms,
        farm_handlers::create_farm,
        farm_handlers::get_farm,
        farm_handlers::edit_farm,
        farm_handlers::get_farm_status,
        farm_handlers::repaint_farm_cells,
        farm_handlers::delete_farm,
        farmer_handlers::send_sign_in_code,
        farmer_handlers::verify_sign_in_code,
        farmer_handlers::get_profile,
        farmer_handlers::update_profile,
        fire_handlers::get_fires,
        fire_handlers::put_fire,
        insight_handlers::get_farm_insights,
        doctor_handlers::ask_doctor,
        insight_handlers::get_farm_coverage,
        insight_handlers::put_farm_insight,
        zone_handlers::get_region_overview,
        zone_handlers::get_zone,
        zone_handlers::get_region_comparison,
        zone_handlers::put_zone_reading,
        zone_handlers::put_sub_zone_reading,
        dam_handlers::get_dams,
        dam_handlers::get_dam_history,
        dam_handlers::put_dam_reading,
        outlook_handlers::get_season_outlook,
        outlook_handlers::get_zone_outlook,
        outlook_handlers::put_zone_outlook,
        outlook_handlers::put_outlook_run,
        water_handlers::get_water_plan,
        water_handlers::put_water_plan_entry,
        water_handlers::delete_water_plan_entry,
        alwa_handlers::get_markets,
        alwa_handlers::get_market_prices,
        alwa_handlers::get_price_history,
        alwa_handlers::get_listings,
        alwa_handlers::get_listing,
        alwa_handlers::get_deals,
        alwa_handlers::create_listing,
        alwa_handlers::get_my_listings,
        alwa_handlers::cancel_listing,
        alwa_handlers::mark_listing_sold,
        alwa_handlers::create_offer,
        alwa_handlers::accept_offer,
        alwa_handlers::get_my_offers,
        alwa_handlers::put_price,
        staff_handlers::sign_in,
        staff_handlers::get_me,
        staff_handlers::get_permission_catalogue,
        staff_handlers::get_roles,
        staff_handlers::create_role,
        staff_handlers::get_role,
        staff_handlers::update_role,
        staff_handlers::delete_role,
        staff_handlers::get_staff_list,
        staff_handlers::create_staff,
        staff_handlers::get_staff,
        staff_handlers::update_staff,
        staff_handlers::delete_staff,
        crate::features::versions::web::handlers::get_versions,
        crate::features::versions::web::handlers::get_dashboard_versions,
        health::liveness,
        health::readiness,
        fire_handlers::get_dashboard_fires,
        fire_handlers::get_dashboard_fire,
        fire_handlers::create_dashboard_fire,
        fire_handlers::update_dashboard_fire,
        fire_handlers::delete_dashboard_fire,
        insight_handlers::get_dashboard_farm_insights,
        insight_handlers::create_dashboard_farm_insight,
        insight_handlers::update_dashboard_farm_insight,
        insight_handlers::delete_dashboard_farm_insight,
        zone_handlers::get_dashboard_zones,
        zone_handlers::get_dashboard_zone_readings,
        zone_handlers::create_dashboard_zone_reading,
        zone_handlers::update_dashboard_zone_reading,
        zone_handlers::delete_dashboard_zone_reading,
        zone_handlers::get_dashboard_sub_zone_readings,
        zone_handlers::create_dashboard_sub_zone_reading,
        zone_handlers::update_dashboard_sub_zone_reading,
        zone_handlers::delete_dashboard_sub_zone_reading,
        farmer_handlers::dashboard_get_farmers,
        farmer_handlers::dashboard_create_farmer,
        farmer_handlers::dashboard_get_farmer,
        farmer_handlers::dashboard_update_farmer,
        farmer_handlers::dashboard_delete_farmer,
        farm_handlers::dashboard_get_farms,
        farm_handlers::dashboard_create_farm,
        farm_handlers::dashboard_get_farm,
        farm_handlers::dashboard_rename_farm,
        farm_handlers::dashboard_delete_farm,
        dam_handlers::dashboard_get_dams,
        dam_handlers::dashboard_get_dam_readings,
        dam_handlers::dashboard_create_dam_reading,
        dam_handlers::dashboard_update_dam_reading,
        dam_handlers::dashboard_delete_dam_reading,
        outlook_handlers::dashboard_get_outlooks,
        outlook_handlers::dashboard_create_outlook,
        outlook_handlers::dashboard_update_outlook,
        outlook_handlers::dashboard_delete_outlook,
        outlook_handlers::dashboard_get_outlook_runs,
        outlook_handlers::dashboard_create_outlook_run,
        outlook_handlers::dashboard_update_outlook_run,
        outlook_handlers::dashboard_delete_outlook_run,
        water_handlers::dashboard_get_water_seasons,
        water_handlers::dashboard_get_water_plan_entries,
        water_handlers::dashboard_create_water_plan_entry,
        water_handlers::dashboard_update_water_plan_entry,
        water_handlers::dashboard_delete_water_plan_entry,
        alwa_dashboard_handlers::get_markets,
        alwa_dashboard_handlers::create_market,
        alwa_dashboard_handlers::update_market,
        alwa_dashboard_handlers::delete_market,
        alwa_dashboard_handlers::get_stored_prices,
        alwa_dashboard_handlers::create_price,
        alwa_dashboard_handlers::update_price,
        alwa_dashboard_handlers::delete_price,
        alwa_dashboard_handlers::get_listings,
        alwa_dashboard_handlers::get_listing,
        alwa_dashboard_handlers::moderate_listing,
        alwa_dashboard_handlers::delete_listing,
        brief_handlers::get_latest_brief,
        brief_handlers::get_briefs,
        brief_handlers::get_farm_brief,
        brief_handlers::put_brief,
        brief_handlers::put_farm_zones,
        brief_handlers::delete_brief,
        brief_handlers::get_dashboard_briefs,
        brief_handlers::update_dashboard_brief,
        brief_handlers::delete_dashboard_brief,
        farmer_handlers::dashboard_issue_letter,
        farmer_handlers::dashboard_get_letter,
        staff_handlers::update_me,
        crate::features::rules::web::handlers::get_rule_values,
        crate::features::rules::web::handlers::dashboard_get_rules,
        crate::features::rules::web::handlers::dashboard_change_rule,
        crate::features::rules::web::handlers::dashboard_get_rule_history,
        crate::features::rules::web::handlers::dashboard_reset_rule,
        crate::features::jobs::web::handlers::put_job_run,
        crate::features::jobs::web::handlers::dashboard_get_jobs,
        farm_handlers::dashboard_get_farm_stats,
        farm_handlers::get_public_farm_stats,
        crate::features::messages::web::handlers::send_message,
        crate::features::messages::web::handlers::get_my_messages,
        crate::features::messages::web::handlers::get_my_message_photo,
        crate::features::messages::web::handlers::dashboard_get_messages,
        crate::features::messages::web::handlers::dashboard_get_message_counts,
        crate::features::messages::web::handlers::dashboard_get_message,
        crate::features::messages::web::handlers::dashboard_set_message_state,
        crate::features::messages::web::handlers::dashboard_reply_to_message,
        crate::features::messages::web::handlers::dashboard_delete_message,
        crate::features::messages::web::handlers::dashboard_get_message_photo,
        crate::features::app_config::web::handlers::get_app_config,
        crate::features::app_config::web::handlers::dashboard_get_app_config,
        crate::features::app_config::web::handlers::dashboard_update_app_config,
        crate::features::app_config::web::handlers::dashboard_get_app_versions,
        crate::features::crops::web::handlers::get_crops,
        crate::features::crops::web::handlers::get_products,
        crate::features::crops::web::handlers::dashboard_get_crops,
        crate::features::crops::web::handlers::dashboard_create_crop,
        crate::features::crops::web::handlers::dashboard_update_crop,
        crate::features::crops::web::handlers::dashboard_delete_crop,
        crate::features::history::web::handlers::get_farm_history,
        crate::features::history::web::handlers::get_history_coverage,
        crate::features::history::web::handlers::put_farm_history,
        crate::features::history::web::handlers::get_dashboard_farm_history,
        crate::features::history::web::handlers::delete_dashboard_farm_history,
        crate::features::plans::web::handlers::get_farm_plan,
        crate::features::plans::web::handlers::get_ingest_farm_plan,
        crate::features::plans::web::handlers::get_plan_coverage,
        crate::features::plans::web::handlers::put_farm_plan,
        crate::features::plans::web::handlers::get_dashboard_farm_plan,
        farmer_handlers::delete_account,
        crate::features::alerts::web::handlers::get_farm_alerts,
        crate::features::alerts::web::handlers::get_my_alerts,
        crate::features::alerts::web::handlers::mark_alert_done,
        crate::features::alerts::web::handlers::register_device,
        crate::features::alerts::web::handlers::delete_device,
        crate::features::alerts::web::handlers::put_alert,
        crate::features::alerts::web::handlers::get_unpushed_alerts,
        crate::features::alerts::web::handlers::mark_alert_pushed,
        crate::features::alerts::web::handlers::delete_dead_device,
        crate::features::alerts::web::handlers::get_dashboard_farm_alerts,
        crate::features::workers::web::handlers::get_workers,
        crate::features::workers::web::handlers::get_my_worker_card,
        crate::features::workers::web::handlers::put_my_worker_card,
        crate::features::workers::web::handlers::delete_my_worker_card,
        crate::features::workers::web::handlers::dashboard_get_workers,
        crate::features::workers::web::handlers::dashboard_delete_worker,
        crate::features::alerts::web::handlers::delete_dashboard_alert
    ),
    components(schemas(
        CreateFarmParams,
        RepaintFarmCellsParams,
        PointParams,
        CellParams,
        FarmSummaryResponse,
        FarmResponse,
        SavedFarmResponse,
        CropAreaResponse,
        CentroidResponse,
        OutlinePointResponse,
        CellResponse,
        GridCellResponse,
        FarmsResponse,
        OneFarmResponse,
        SendSignInCodeParams,
        SignInCodeSentResponse,
        VerifySignInCodeParams,
        SignedInResponse,
        EditProfileParams,
        ProfileResponse,
        Language,
        RecordFireParams,
        FireResponse,
        FireSummaryResponse,
        FiresResponse,
        FireStatus,
        WindDirection,
        RecordFarmInsightParams,
        MeasureParams,
        MeasureResponse,
        TopicInsightResponse,
        FarmInsightsResponse,
        TopicStampResponse,
        FarmCoverageResponse,
        FarmsCoverageResponse,
        Topic,
        Confidence,
        RegionOverviewResponse,
        ZoneOverviewResponse,
        RegionSummaryResponse,
        ZoneDetailResponse,
        ZoneDetailReadingResponse,
        SubZoneDrynessResponse,
        YearDrynessResponse,
        RegionComparisonResponse,
        ZoneComparisonResponse,
        YearAverageResponse,
        ZoneReadingParams,
        ZoneReadingResponse,
        SubZoneReadingParams,
        SubZoneReadingResponse,
        DrynessBand,
        BestCrop,
        DamsResponse,
        DamResponse,
        LatestReadingResponse,
        YearAgoReadingResponse,
        DamHistoryResponse,
        HistoryReadingResponse,
        RecordDamReadingParams,
        SavedDamReadingResponse,
        DamReadingResponse,
        SeasonOutlookResponse,
        OutlookCountsResponse,
        ZoneOutlookResponse,
        TrackRecordResponse,
        ZoneOutlookHistoryResponse,
        ZoneIssueResponse,
        RecordZoneOutlookParams,
        SavedZoneOutlookResponse,
        StoredZoneOutlookResponse,
        RecordOutlookRunParams,
        SavedOutlookRunResponse,
        OutlookRunResponse,
        Outlook,
        WaterPlanResponse,
        RankedEntryResponse,
        PlanTotalsResponse,
        DamAllocationResponse,
        SetWaterPlanEntryParams,
        SavedWaterPlanEntryResponse,
        StoredWaterPlanEntryResponse,
        FarmStatusResponse,
        CropStatusResponse,
        CellStatusResponse,
        Level,
        AlwaGrade,
        AlwaPickup,
        AlwaProductGroup,
        AlwaUnit,
        AlwaListingStatus,
        AlwaOfferStatus,
        AlwaBuyerKind,
        AlwaFairPrice,
        AlwaMarketResponse,
        AlwaMarketsResponse,
        AlwaPriceResponse,
        AlwaMarketPricesResponse,
        AlwaPricePointResponse,
        AlwaPriceHistoryResponse,
        RecordAlwaPriceParams,
        AlwaRecordedPriceResponse,
        AlwaOnePriceResponse,
        AlwaListingSummaryResponse,
        AlwaListingsResponse,
        PostAlwaListingParams,
        AlwaListingResponse,
        AlwaOneListingResponse,
        AlwaMyListingsResponse,
        MakeAlwaOfferParams,
        AlwaOfferResponse,
        AlwaOneOfferResponse,
        AlwaOfferListingResponse,
        AlwaMyOfferResponse,
        AlwaMyOffersResponse,
        AlwaDealResponse,
        AlwaDealsSummaryResponse,
        AlwaDealsResponse,
        StaffLoginParams,
        StaffSignedInResponse,
        StaffMeResponse,
        StaffPermissionCatalogueResponse,
        StaffPermission,
        StaffResource,
        StaffAction,
        StaffResponse,
        StaffRoleRefResponse,
        StaffOneResponse,
        StaffListResponse,
        CreateStaffParams,
        UpdateStaffParams,
        SaveStaffRoleParams,
        StaffRoleResponse,
        StaffOneRoleResponse,
        StaffRolesResponse,
        FireDashboardCreateParams,
        FireDashboardResponse,
        FireDashboardOneResponse,
        FireDashboardListResponse,
        InsightDashboardCreateParams,
        InsightDashboardResponse,
        InsightDashboardOneResponse,
        InsightDashboardListResponse,
        ZoneDashboardZonesResponse,
        ZoneDashboardZoneResponse,
        ZoneDashboardSubZoneResponse,
        ZoneDashboardReadingsResponse,
        ZoneDashboardSubZoneReadingsResponse,
        CreateZoneDashboardReadingParams,
        CreateZoneDashboardSubZoneReadingParams,
        DashboardCreateFarmerParams,
        DashboardUpdateFarmerParams,
        DashboardFarmerResponse,
        DashboardOneFarmerResponse,
        DashboardFarmersResponse,
        DashboardCreateFarmParams,
        DashboardRenameFarmParams,
        DashboardFarmSummaryResponse,
        DashboardFarmsResponse,
        DashboardFarmResponse,
        DashboardOneFarmResponse,
        DashboardSavedFarmResponse,
        CreateDamDashboardReadingParams,
        DamReferenceResponse,
        DamReferencesResponse,
        DamReadingsPageResponse,
        CreateOutlookDashboardParams,
        CreateOutlookRunDashboardParams,
        OutlooksPageResponse,
        OutlookRunsResponse,
        CreateWaterPlanEntryDashboardParams,
        WaterSeasonsResponse,
        WaterPlanEntriesResponse,
        CreateAlwaMarketParams,
        UpdateAlwaMarketParams,
        AlwaOneMarketResponse,
        AlwaStoredPricesResponse,
        CreateAlwaPriceParams,
        AlwaModeratedListingResponse,
        AlwaModeratedListingsResponse,
        AlwaModeratedOfferResponse,
        AlwaModeratedListingDetailResponse,
        AlwaOneModeratedListingResponse,
        ModerateAlwaListingParams,
        RecordBriefParams,
        BriefPointParams,
        BriefSourceParams,
        BriefPointLevel,
        RecordBriefFarmZonesParams,
        BriefFarmZoneParams,
        BriefResponse,
        BriefPointResponse,
        BriefSourceResponse,
        OneBriefResponse,
        BriefsResponse,
        FarmBriefResponse,
        BriefFarmZonesRecordedResponse,
        BriefsPageResponse,
        DoctorAskForm,
        DoctorAnswerResponse,
        DoctorConfidence,
        crate::features::versions::web::VersionsResponse,
        FarmerGender,
        FarmerLetterLanguage,
        DashboardFarmerSort,
        DashboardFarmerOrder,
        DashboardIssueLetterParams,
        DashboardLetterIssuerResponse,
        DashboardLetterFarmerResponse,
        DashboardLetterCropResponse,
        DashboardLetterFarmResponse,
        DashboardLetterTotalsResponse,
        DashboardIssuedLetterResponse,
        DashboardOneIssuedLetterResponse,
        DashboardLetterRecordResponse,
        DashboardOneLetterRecordResponse,
        UpdateOwnStaffProfileParams,
        crate::features::rules::web::RuleUsedBy,
        crate::features::rules::web::RuleResponse,
        crate::features::rules::web::RulesResponse,
        crate::features::rules::web::OneRuleResponse,
        crate::features::rules::web::ChangeRuleParams,
        crate::features::rules::web::ResetRuleParams,
        crate::features::rules::web::RuleChangeResponse,
        crate::features::rules::web::RuleHistoryResponse,
        crate::features::rules::web::RuleValueResponse,
        crate::features::rules::web::RuleValuesResponse,
        crate::features::jobs::web::JobRunState,
        crate::features::jobs::web::JobDayMark,
        crate::features::jobs::web::RecordJobRunParams,
        crate::features::jobs::web::JobRunResponse,
        crate::features::jobs::web::SavedJobRunResponse,
        crate::features::jobs::web::JobStatusResponse,
        crate::features::jobs::web::JobsResponse,
        crate::features::farms::web::FarmStatsResponse,
        crate::features::farms::web::PublicFarmStatsResponse,
        crate::features::farms::web::FarmStatsTotalsResponse,
        crate::features::farms::web::FarmStatsAreaResponse,
        crate::features::farms::web::FarmStatsAreaCropResponse,
        crate::features::farms::web::FarmStatsCropResponse,
        crate::features::messages::web::MessageSendForm,
        crate::features::messages::web::InboxMessageKind,
        crate::features::messages::web::InboxMessageState,
        crate::features::messages::web::MessagePhotoResponse,
        crate::features::messages::web::MessageReplyResponse,
        crate::features::messages::web::MessageResponse,
        crate::features::messages::web::OneMessageResponse,
        crate::features::messages::web::MyMessagesResponse,
        crate::features::messages::web::DashboardMessageReplyResponse,
        crate::features::messages::web::DashboardMessageResponse,
        crate::features::messages::web::DashboardOneMessageResponse,
        crate::features::messages::web::DashboardMessagesResponse,
        crate::features::messages::web::MessageCountsResponse,
        crate::features::messages::web::SetMessageStateParams,
        crate::features::messages::web::ReplyToMessageParams,
        crate::features::app_config::web::AppFeaturesDto,
        crate::features::app_config::web::AppLimitsDto,
        crate::features::app_config::web::AppConfigResponse,
        crate::features::app_config::web::DashboardAppConfigResponse,
        crate::features::app_config::web::UpdateAppConfigParams,
        crate::features::app_config::web::AppVersionUsageResponse,
        crate::features::app_config::web::AppVersionsResponse,
        crate::features::crops::web::CropCategory,
        crate::features::crops::web::CropSeason,
        crate::features::crops::web::CropResponse,
        crate::features::crops::web::CropsResponse,
        crate::features::crops::web::ProductGroup,
        crate::features::crops::web::ProductUnit,
        crate::features::crops::web::ProductResponse,
        crate::features::crops::web::ProductsResponse,
        crate::features::crops::web::OneCropResponse,
        crate::features::crops::web::CreateCropParams,
        crate::features::crops::web::UpdateCropParams,
        crate::features::history::web::HistoryMetric,
        crate::features::history::web::RecordFarmHistoryParams,
        crate::features::history::web::HistoryPointParams,
        crate::features::history::web::HistoryRecordedResponse,
        crate::features::history::web::FarmHistoryResponse,
        crate::features::history::web::HistorySeriesResponse,
        crate::features::history::web::HistoryMonthResponse,
        crate::features::history::web::HistoryYearResponse,
        crate::features::history::web::HistoryCoverageResponse,
        crate::features::history::web::HistoryFarmCoverageResponse,
        crate::features::history::web::HistoryMetricCoverageResponse,
        crate::features::plans::web::PlanAlertType,
        crate::features::plans::web::PlanAlertLevel,
        crate::features::plans::web::PlanDecisionCode,
        crate::features::plans::web::PlanAlertParams,
        crate::features::plans::web::PlanDecisionParams,
        crate::features::plans::web::RecordFarmPlanParams,
        crate::features::plans::web::PlanAlertResponse,
        crate::features::plans::web::PlanDecisionResponse,
        crate::features::plans::web::FarmPlanResponse,
        crate::features::plans::web::PlanCoverageFarmResponse,
        crate::features::plans::web::PlanCoverageResponse,
        crate::features::plans::web::PlanDashboardStoredResponse,
        crate::features::plans::web::PlanDashboardResponse,
        crate::features::alerts::web::AlertType,
        crate::features::alerts::web::AlertLevel,
        crate::features::alerts::web::AlertConfidence,
        crate::features::alerts::web::AlertPlatform,
        crate::features::alerts::web::AlertResponse,
        crate::features::alerts::web::AlertsResponse,
        crate::features::alerts::web::RecordAlertParams,
        crate::features::alerts::web::AlertDashboardResponse,
        crate::features::alerts::web::AlertDashboardListResponse,
        crate::features::alerts::web::AlertPendingPushResponse,
        crate::features::alerts::web::AlertPendingPushesResponse,
        crate::features::alerts::web::AlertNotifyParams,
        crate::features::alerts::web::AlertDeviceResponse,
        crate::features::alerts::web::RegisterDeviceParams,
        crate::features::workers::web::WorkerCostPer,
        crate::features::workers::web::PutWorkerParams,
        crate::features::workers::web::WorkerResponse,
        crate::features::workers::web::OneWorkerResponse,
        crate::features::workers::web::MyWorkerResponse,
        crate::features::workers::web::WorkerCardResponse,
        crate::features::workers::web::WorkersResponse,
        crate::features::workers::web::DashboardWorkerResponse,
        crate::features::workers::web::DashboardWorkersResponse,
        ErrorBody
    )),
    modifiers(&BearerAuth),
    tags(
        (name = "farm-doctor-api", description = "Farm Doctor API"),
        (name = "farmers", description = "Sign in with a phone and a code, and the farmer's profile"),
        (name = "farms", description = "A farmer's farms: outline, cell grid and crops"),
        (name = "fires", description = "Satellite fire detections for the Ministry dashboard"),
        (name = "insights", description = "What the data jobs know about a farm, topic by topic"),
        (name = "doctor", description = "Ask the Doctor: a farmer's question about one farm, answered by the local Doctor service"),
        (name = "zones", description = "The region's districts: dryness, rain, greenness and advice per month"),
        (name = "dams", description = "The large dams: how full they are now, a year ago and over time"),
        (name = "outlooks", description = "The Doctor: the outlook for the next growing season, zone by zone"),
        (name = "water", description = "The plan for which zones should receive water first"),
        (name = "alwa", description = "The wholesale produce markets: prices, crops on sale, offers and deals"),
        (name = "staff", description = "The dashboard's staff accounts, custom roles and sign-in"),
        (name = "briefs", description = "The daily brief the nightly job writes for the region and for each zone"),
        (name = "rules", description = "The numbers the data jobs use to decide a warning or a colour, changed by staff with a logged reason"),
        (name = "jobs", description = "Whether the automatic data jobs ran on time: each job reports its runs, staff read how they stand"),
        (name = "messages", description = "The inbox: messages farmers send to the Ministry, with photos, and the replies"),
        (name = "app", description = "App control: what the farmer app reads at start, and which versions are in use"),
        (name = "crops", description = "The crop list staff keep: the codes farms, listings and prices may use, with names and colours"),
        (name = "history", description = "Ten years of monthly history per farm: rain, temperature, evapotranspiration, soil moisture, greenness and groundwater"),
        (name = "plans", description = "This week's plan: the next 10 days of weather turned into farm work, pushed per farm by the plan job"),
        (name = "workers", description = "Workers for hire: people put up a card with their name, phone and cost, and farmers call them"),
        (name = "alerts", description = "Alerts for a farm: what the data jobs warn about, what the farmer ticked, and the phones registered for pushes")
    ),
    info(
        title = "farm-doctor-api",
        version = "1.0.0",
        description = "API behind the farmer app and the Ministry dashboard."
    ),
    servers((url = "/", description = "API"))
)]
pub struct ApiDoc;

pub fn swagger_ui() -> SwaggerUi {
    SwaggerUi::new("/api-docs").url("/api-docs/openapi.json", ApiDoc::openapi())
}
