//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "dam_readings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "idx_dam_readings_dam_id_day")]
    pub dam_id: i32,
    #[sea_orm(unique_key = "idx_dam_readings_dam_id_day")]
    pub day: Date,
    #[sea_orm(column_type = "Double")]
    pub pct_full: f64,
    #[sea_orm(column_type = "Double", nullable)]
    pub volume_bn_m3: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub lake_area_km2: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub farm_supply_bn_m3: Option<f64>,
    pub source: String,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dams::Entity",
        from = "Column::DamId",
        to = "super::dams::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Dams,
}

impl Related<super::dams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dams.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
