//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "dams")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub slug: String,
    pub name_en: String,
    pub name_ku: String,
    #[sea_orm(column_type = "Double")]
    pub capacity_bn_m3: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::dam_readings::Entity")]
    DamReadings,
}

impl Related<super::dam_readings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DamReadings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
