//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "alerts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "idx_alerts_farm_id_key")]
    pub farm_id: i32,
    #[sea_orm(unique_key = "idx_alerts_farm_id_key")]
    pub key: String,
    pub r#type: String,
    pub day: Date,
    pub level: String,
    pub confidence: String,
    pub ku: String,
    pub en: String,
    pub action_ku: String,
    pub action_en: String,
    pub pushed: bool,
    pub pushed_at: Option<DateTime>,
    pub done: bool,
    pub done_at: Option<DateTime>,
    pub source: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
