//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "farm_plans")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub farm_id: i32,
    pub from_day: Date,
    pub issued: DateTime,
    #[sea_orm(column_type = "JsonBinary")]
    pub rain_mm: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub tmin: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub tmax: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub alerts: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub decisions: Json,
    pub source: String,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
