//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "rule_changes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub code: String,
    #[sea_orm(column_type = "Double")]
    pub old_value: f64,
    #[sea_orm(column_type = "Double")]
    pub new_value: f64,
    pub reason: String,
    pub staff_id: i32,
    pub at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::rules::Entity",
        from = "Column::Code",
        to = "super::rules::Column::Code",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Rules,
}

impl Related<super::rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Rules.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
