//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "rules")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub code: String,
    pub grp: String,
    pub name_en: String,
    pub name_ku: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub meaning_en: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub meaning_ku: Option<String>,
    #[sea_orm(column_type = "Double")]
    pub value: f64,
    pub unit: String,
    #[sea_orm(column_type = "Double")]
    pub min_value: f64,
    #[sea_orm(column_type = "Double")]
    pub max_value: f64,
    #[sea_orm(column_type = "Double")]
    pub default_value: f64,
    pub used_by: String,
    pub updated_by: Option<i32>,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::rule_changes::Entity")]
    RuleChanges,
}

impl Related<super::rule_changes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RuleChanges.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
