//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "app_config")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i16,
    pub latest_version: String,
    pub min_version: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub update_message_ku: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub update_message_en: Option<String>,
    pub maintenance: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub maintenance_message_ku: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub maintenance_message_en: Option<String>,
    pub maintenance_from: Option<DateTime>,
    pub maintenance_until: Option<DateTime>,
    pub announcement_on: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub announcement_ku: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub announcement_en: Option<String>,
    pub feature_add_farm: bool,
    pub feature_walk_mode: bool,
    pub feature_satellite: bool,
    pub feature_doctor: bool,
    pub feature_reports: bool,
    pub feature_alwa: bool,
    pub feature_plan: bool,
    pub feature_push: bool,
    pub limit_farms_per_phone: i32,
    pub limit_max_farm_dunam: i32,
    pub limit_min_corners: i32,
    pub limit_max_corners: i32,
    pub limit_gps_meters: i32,
    pub help_phone: Option<String>,
    pub public_farm_totals: bool,
    pub updated_by: Option<i32>,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
