//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "season_outlooks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "idx_season_outlooks_zone_slug_season_issued")]
    pub zone_slug: String,
    #[sea_orm(unique_key = "idx_season_outlooks_zone_slug_season_issued")]
    pub season: String,
    #[sea_orm(unique_key = "idx_season_outlooks_zone_slug_season_issued")]
    pub issued: Date,
    pub outlook: String,
    #[sea_orm(column_type = "Double")]
    pub confidence_pct: f64,
    pub reason_en: Option<String>,
    pub reason_ku: Option<String>,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
