//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "farm_insights")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "idx_farm_insights_farm_id_topic")]
    pub farm_id: i32,
    #[sea_orm(unique_key = "idx_farm_insights_farm_id_topic")]
    pub topic: String,
    pub as_of: Date,
    pub source: String,
    pub confidence: String,
    pub summary_en: Option<String>,
    pub summary_ku: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub measures: Json,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
