//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "workers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub phone: String,
    pub name: String,
    pub cost_iqd: i32,
    pub cost_per: String,
    pub note: Option<String>,
    pub zone_slug: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub lat: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub lon: Option<f64>,
    pub available: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
