//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "fires")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub external_id: String,
    #[sea_orm(column_type = "Double")]
    pub lat: f64,
    #[sea_orm(column_type = "Double")]
    pub lon: f64,
    pub zone_slug: Option<String>,
    pub place_en: Option<String>,
    pub place_ku: Option<String>,
    pub detected_at: DateTime,
    #[sea_orm(column_type = "Double", nullable)]
    pub area_ha: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub wind_kmh: Option<f64>,
    pub wind_direction: Option<String>,
    pub status: String,
    #[sea_orm(column_name = "farms_within_5km")]
    pub farms_within_5km: Option<i32>,
    pub farmers_alerted: Option<i32>,
    pub source: String,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
