//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "messages")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "idx_messages_farmer_id_idempotency_key")]
    pub farmer_id: i32,
    pub farm_id: Option<i32>,
    pub kind: String,
    #[sea_orm(column_type = "Text")]
    pub text: String,
    pub state: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub reply_text_ku: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub reply_text_en: Option<String>,
    pub replied_by: Option<i32>,
    pub replied_at: Option<DateTime>,
    #[sea_orm(unique_key = "idx_messages_farmer_id_idempotency_key")]
    pub idempotency_key: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::message_photos::Entity")]
    MessagePhotos,
}

impl Related<super::message_photos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MessagePhotos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
